# Generated by Django 5.0.1 on 2025-06-01 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkAnalysisQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='Consulta')),
                ('response', models.TextField(verbose_name='Respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de consulta')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo de procesamiento (segundos)')),
                ('cvs_analyzed', models.ManyToManyField(to='cvs.cv', verbose_name='CVs analizados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Consulta masiva de análisis',
                'verbose_name_plural': 'Consultas masivas de análisis',
                'ordering': ['-created_at'],
            },
        ),
    ]
