# Generated by Django 5.0.1 on 2026-05-15 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0002_bulkanalysisquery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisquery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Consulta individual', 'verbose_name_plural': 'Consultas individuales'},
        ),
        migrations.AlterModelOptions(
            name='bulkanalysisquery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comparativa IA', 'verbose_name_plural': 'Comparativas IA'},
        ),
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Perfil profesional', 'verbose_name_plural': 'Perfiles profesionales'},
        ),
        migrations.AddField(
            model_name='cv',
            name='extracted_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto extraído del perfil'),
        ),
        migrations.AddField(
            model_name='cv',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento'),
        ),
        migrations.AddField(
            model_name='cv',
            name='processing_error',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle del error de procesamiento'),
        ),
        migrations.AddField(
            model_name='cv',
            name='text_length',
            field=models.PositiveIntegerField(default=0, verbose_name='Longitud del texto extraído'),
        ),
        migrations.AlterField(
            model_name='analysisquery',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='cvs.cv', verbose_name='Perfil profesional'),
        ),
        migrations.AlterField(
            model_name='analysisquery',
            name='response',
            field=models.TextField(verbose_name='Respuesta del motor IA'),
        ),
        migrations.AlterField(
            model_name='bulkanalysisquery',
            name='cvs_analyzed',
            field=models.ManyToManyField(to='cvs.cv', verbose_name='Perfiles analizados'),
        ),
        migrations.AlterField(
            model_name='bulkanalysisquery',
            name='processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo de procesamiento en segundos'),
        ),
        migrations.AlterField(
            model_name='bulkanalysisquery',
            name='query',
            field=models.TextField(verbose_name='Consulta comparativa'),
        ),
        migrations.AlterField(
            model_name='bulkanalysisquery',
            name='response',
            field=models.TextField(verbose_name='Respuesta comparativa del motor IA'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='analysis_result',
            field=models.TextField(blank=True, null=True, verbose_name='Resultado del análisis inicial'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cargado por'),
        ),
    ]
