# Generated by Django 5.0.1 on 2026-05-27 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0003_alter_analysisquery_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(verbose_name='Descripción del puesto')),
                ('response', models.TextField(verbose_name='Resultado del matching IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de evaluación')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo de procesamiento en segundos')),
                ('cvs_analyzed', models.ManyToManyField(to='cvs.cv', verbose_name='Perfiles evaluados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Matching contra puesto',
                'verbose_name_plural': 'Matchings contra puestos',
                'ordering': ['-created_at'],
            },
        ),
    ]
