# Generated by Django 5.0.1 on 2026-05-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0004_jobmatchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisquery',
            name='detected_education',
            field=models.TextField(blank=True, null=True, verbose_name='Educación detectada'),
        ),
        migrations.AddField(
            model_name='analysisquery',
            name='detected_languages',
            field=models.TextField(blank=True, null=True, verbose_name='Idiomas detectados'),
        ),
        migrations.AddField(
            model_name='analysisquery',
            name='detected_roles',
            field=models.TextField(blank=True, null=True, verbose_name='Roles detectados'),
        ),
        migrations.AddField(
            model_name='analysisquery',
            name='detected_skills',
            field=models.TextField(blank=True, null=True, verbose_name='Skills detectadas'),
        ),
        migrations.AddField(
            model_name='analysisquery',
            name='detected_universities',
            field=models.TextField(blank=True, null=True, verbose_name='Universidades detectadas'),
        ),
        migrations.AddField(
            model_name='analysisquery',
            name='seniority',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Seniority detectado'),
        ),
        migrations.AddField(
            model_name='analysisquery',
            name='structured_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos estructurados IA'),
        ),
        migrations.AddField(
            model_name='cv',
            name='detected_education',
            field=models.TextField(blank=True, null=True, verbose_name='Educación detectada'),
        ),
        migrations.AddField(
            model_name='cv',
            name='detected_experience',
            field=models.TextField(blank=True, null=True, verbose_name='Experiencia detectada'),
        ),
        migrations.AddField(
            model_name='cv',
            name='detected_institutions',
            field=models.TextField(blank=True, null=True, verbose_name='Instituciones detectadas'),
        ),
        migrations.AddField(
            model_name='cv',
            name='detected_roles',
            field=models.TextField(blank=True, null=True, verbose_name='Puestos detectados'),
        ),
        migrations.AddField(
            model_name='cv',
            name='detected_skills',
            field=models.TextField(blank=True, null=True, verbose_name='Habilidades detectadas'),
        ),
        migrations.AddField(
            model_name='cv',
            name='structured_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos estructurados del perfil'),
        ),
    ]
